# Generated by Django 6.0 on 2026-09-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolution_image',
            field=models.ImageField(blank=True, null=True, upload_to='resolution_images/'),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='student_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='student_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='student_verified',
            field=models.BooleanField(default=False),
        ),
    ]
