# Generated by Django 6.0.6 on 2026-09-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('cleaning', 'Cleaning'), ('it', 'Wi-Fi/IT'), ('equipment', 'Classroom Equipment'), ('security', 'Security'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
